/*
 * Morgan Stanley makes this available to you under the Apache License, Version 2.0 (the "License").
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
 * See the NOTICE file distributed with this work for additional information regarding copyright ownership.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package optimus.platform.annotations;

import java.lang.annotation.*;

/**
 * A def returning a Seq[Tweak] should be annotated with @handle. OptimusUI warns of its absence on
 * such a def which is bound to a widget. The async parameter instructs OptimusUI to NOT block the
 * GUI thread for the tweaks (generated by the def) to be added to the scenario.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface handle {}
