package optimus.platform.dsi.bitemporal.proto

object Dsi {
  trait MessageLiteImpl extends com.google.protobuf.MessageLite {
    def getParserForType(): com.google.protobuf.Parser[_ <: com.google.protobuf.MessageLite] = ???
    def getSerializedSize(): Int = ???
    def newBuilderForType(): com.google.protobuf.MessageLite.Builder = ???
    def toBuilder(): com.google.protobuf.MessageLite.Builder = ???
    def toByteArray(): Array[Byte] = ???
    def toByteString(): com.google.protobuf.ByteString = ???
    def writeDelimitedTo(output: java.io.OutputStream): Unit = ???
    def writeTo(output: java.io.OutputStream): Unit = ???
    def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = ???
    def getDefaultInstanceForType(): com.google.protobuf.MessageLite = ???
    def isInitialized(): Boolean = ???
  }

  class TemporalityProto extends MessageLiteImpl
  class PrcClientSessionInfoProto extends MessageLiteImpl
  class ContextProto extends MessageLiteImpl
  class PrcUserOptionsProto extends MessageLiteImpl
  class NonTemporalPrcKeyProto extends MessageLiteImpl
  class NormalizedCacheableQueryProto extends MessageLiteImpl
  class ChainedIdProto extends MessageLiteImpl
  class QueryEntityMetadataProto extends MessageLiteImpl
  class QueryEntityMetadataResultProto extends MessageLiteImpl
  class EntityMetadataProto extends MessageLiteImpl
  class SelectBusinessEventTimelineResultProto extends MessageLiteImpl
  class PartialSelectBusinessEventTimelineResultProto extends MessageLiteImpl
  class SelectBusinessEventValidTimelineResultProto extends MessageLiteImpl
  class SelectBusinessEventValidTimelineLazyLoadResultProto extends MessageLiteImpl
  class SerializedAppEventProto extends MessageLiteImpl
  class SerializedKeyProto extends MessageLiteImpl
  class InstantProto extends MessageLiteImpl
  class SinglePropertyLinkageProto extends MessageLiteImpl
  class SerializedEntityProto extends MessageLiteImpl
  class SerializedBusinessEventWithTTToProto extends MessageLiteImpl
  class PersistentEntityProto extends MessageLiteImpl
  class ValidTimeIntervalProto extends MessageLiteImpl
  class VersionedReferenceProto extends MessageLiteImpl
  class StorableReferenceProto extends MessageLiteImpl
  class EntityTimeSliceReferenceProto extends MessageLiteImpl
  class EntityReferenceProto extends MessageLiteImpl
  class BusinessEventReferenceProto extends MessageLiteImpl
  class AppEventReferenceProto extends MessageLiteImpl
  class CmReferenceProto extends MessageLiteImpl
  class TimeIntervalProto extends MessageLiteImpl
  class PersistentEntityWithTemporalContextProto extends MessageLiteImpl
  class SerializedBusinessEventProto extends MessageLiteImpl
  class SlotMapProto extends MessageLiteImpl
  class ClientAppIdentifierProto extends MessageLiteImpl
  class CommandProto extends MessageLiteImpl
  class ResultProto extends MessageLiteImpl
  class VersioningResultProto extends MessageLiteImpl
  class ErrorResultProto extends MessageLiteImpl
  class CountGroupingsProto extends MessageLiteImpl
  class CountProto extends MessageLiteImpl
  class SelectProto extends MessageLiteImpl
  class SelectSpaceProto extends MessageLiteImpl
  class SelectSpaceResultRectangleProto extends MessageLiteImpl
  class SelectSpaceResultProto extends MessageLiteImpl
  class PartialSelectSpaceResultProto extends MessageLiteImpl
  class GetAuditInfoProto extends MessageLiteImpl
  class EntityAuditInfoProto extends MessageLiteImpl
  class SelectBusinesEventByKeyProto extends MessageLiteImpl
  class SelectBusinesEventByEventClassProto extends MessageLiteImpl
  class SelectBusinesEventByEventRefProto extends MessageLiteImpl
  class GetInitiatingEventProto extends MessageLiteImpl
  class SelectBusinesEventByEntityRefProto extends MessageLiteImpl
  class SelectEntityEventValidTimelineProto extends MessageLiteImpl
  class SelectEventTimelineProto extends MessageLiteImpl
  class GetEventTransactionsProto extends MessageLiteImpl
  class SelectBusinessEventAssociatedEntitiesProto extends MessageLiteImpl
  class JarPathProto extends MessageLiteImpl
  class ClientMachineIdentifierProto extends MessageLiteImpl
  class EstablishSessionProto extends MessageLiteImpl
  class TokenProto extends MessageLiteImpl
  class EstablishSessionResultProto extends MessageLiteImpl
  class TypeProto extends MessageLiteImpl
  class SessionTokenRequestProto extends MessageLiteImpl
  class CreateNewSessionProto extends MessageLiteImpl
  class CreateNewSessionResultProto extends MessageLiteImpl
  class DiscoverServicesProto extends MessageLiteImpl
  class DiscoverServicesResultProto extends MessageLiteImpl
  class ServiceDiscoveryElementProto extends MessageLiteImpl
  class ProviderProto extends MessageLiteImpl
  class LookupTypeProto extends MessageLiteImpl
  class SessionTokenResultProto extends MessageLiteImpl
  class HeartbeatProto extends MessageLiteImpl
  class HeartbeatResultProto extends MessageLiteImpl
  class GetProtoFilePropertiesProto extends MessageLiteImpl
  class GetProtoFilePropertiesResultProto extends MessageLiteImpl
  class SelectResultProto extends MessageLiteImpl
  class ResultStatsProto extends MessageLiteImpl
  class GetAuditInfoResultProto extends MessageLiteImpl
  class PartialGetAuditInfoResultProto extends MessageLiteImpl
  class SelectBusinessEventResultProto extends MessageLiteImpl
  class PartialSelectBusinessEventResultProto extends MessageLiteImpl
  class SelectBusinessEventWithTTToResultProto extends MessageLiteImpl
  class GetInitiatingEventResultProto extends MessageLiteImpl
  class PartialSelectResultProto extends MessageLiteImpl
  class PrcPartialSelectResultProto extends MessageLiteImpl
  class CountResultProto extends MessageLiteImpl
  class FeatureInfoProto extends MessageLiteImpl
  class GetInfoResultProto extends MessageLiteImpl
  class LsqtProto extends MessageLiteImpl
  class RoleMembershipQueryProto extends MessageLiteImpl
  class CanPerformActionProto extends MessageLiteImpl
  class BooleanResultProto extends MessageLiteImpl
  class RoleMembershipResultProto extends MessageLiteImpl
  class TemporalityQueryCommandProto extends MessageLiteImpl
  class TimesFromProto extends MessageLiteImpl
  class FromProto extends MessageLiteImpl
  class QueryReferenceResultProto extends MessageLiteImpl
  class PartialQueryReferenceResultProto extends MessageLiteImpl
  class GetRefsNotAtSlotProto extends MessageLiteImpl
  class GetRefsNotAtSlotResultProto extends MessageLiteImpl
  class GetSlotsProto extends MessageLiteImpl
  class GetSlotsResultProto extends MessageLiteImpl
  class ExpressionQueryCommandProto extends MessageLiteImpl
  class ReferenceQueryProto extends MessageLiteImpl
  class EventReferenceQueryProto extends MessageLiteImpl
  class SerializedKeyQueryProto extends MessageLiteImpl
  class EventSerializedKeyQueryProto extends MessageLiteImpl
  class LinkageQueryProto extends MessageLiteImpl
  class EntityClassQueryProto extends MessageLiteImpl
  class EventClassQueryProto extends MessageLiteImpl
  class EntityCmReferenceQueryProto extends MessageLiteImpl
  class EventCmReferenceQueryProto extends MessageLiteImpl
  class SystemResultProto extends MessageLiteImpl
  class SystemProto extends MessageLiteImpl
  class ObliterateProto extends MessageLiteImpl
  class RolesetModeProto extends MessageLiteImpl
  class RolesetProto extends MessageLiteImpl
  class NotificationMessageProto extends MessageLiteImpl
  class NotifyHeartBeatProto extends MessageLiteImpl
  class ResetStateProto extends MessageLiteImpl
  class BeginTransactionProto extends MessageLiteImpl
  class EndTransactionProto extends MessageLiteImpl
  class NotificationEntryProto extends MessageLiteImpl
  class ObliterateMessageProto extends MessageLiteImpl
  class CreatePubSubStreamProto extends MessageLiteImpl
  class ChangeSubscriptionProto extends MessageLiteImpl
  class ClosePubSubStreamProto extends MessageLiteImpl
  class SubscriptionProto extends MessageLiteImpl
  class QueryHolderProto extends MessageLiteImpl
  class CreatePubSubStreamSuccessProto extends MessageLiteImpl
  class ChangeSubscriptionSuccessProto extends MessageLiteImpl
  class ClosePubSubStreamSuccessProto extends MessageLiteImpl
  class PubSubSowResultProto extends MessageLiteImpl
  class PubSubNotificationProto extends MessageLiteImpl
  class PubSubNotificationPartialResultProto extends MessageLiteImpl
  class PubSubHeartbeatProto extends MessageLiteImpl
  class PartitionToSubIdsMapProto extends MessageLiteImpl
  class PubSubStreamEventProto extends MessageLiteImpl
  class PubSubGlobalEventProto extends MessageLiteImpl
  class EnumerateKeysProto extends MessageLiteImpl
  class EnumerateKeysResultProto extends MessageLiteImpl
  class EnumerateIndicesProto extends MessageLiteImpl
  class EnumerateIndicesResultProto extends MessageLiteImpl
  class PartialEnumerateIndicesResultProto extends MessageLiteImpl
  class PartialEnumerateKeysResultProto extends MessageLiteImpl
  class PublishMessagesProto extends MessageLiteImpl
  class PublishTransactionProto extends MessageLiteImpl
  class CreateMessagesStreamProto extends MessageLiteImpl
  class ChangeMessagesSubscriptionProto extends MessageLiteImpl
  class CloseMessagesStreamProto extends MessageLiteImpl
  class CommitMessagesStreamProto extends MessageLiteImpl
  class PublishMessagesSuccessProto extends MessageLiteImpl
  class CreateMessagesStreamSuccessProto extends MessageLiteImpl
  class ChangeMessagesSubscriptionSuccessProto extends MessageLiteImpl
  class CloseMessagesStreamSuccessProto extends MessageLiteImpl
  class MessagesNotificationProto extends MessageLiteImpl
  class MessagesNotificationEntryProto extends MessageLiteImpl
  class MessagesTransactionNotificationEntryProto extends MessageLiteImpl
  class SerializedMessageProto extends MessageLiteImpl
  class EntityReferenceToContainedEntityProto extends MessageLiteImpl
  class ContainedEntityProto extends MessageLiteImpl
  class MessagesSubscriptionProto extends MessageLiteImpl
  class SerializedTransactionProto extends MessageLiteImpl
  class StreamsACLsCommandProto extends MessageLiteImpl
  class StreamsACLsProto extends MessageLiteImpl
  class HierarchicalEntitiesProto extends MessageLiteImpl
  class StreamsACLsCommandSuccessProto extends MessageLiteImpl
  class CommandAppNameTagProto extends MessageLiteImpl
  class FieldProto extends MessageLiteImpl
  class CommandLocationProto extends MessageLiteImpl
  class PartialQueryResultProto extends MessageLiteImpl
  class QueryResultProto extends MessageLiteImpl
  class ValuesProto extends MessageLiteImpl
  class ValueProto extends MessageLiteImpl
  class QueryResultMetaDataProto extends MessageLiteImpl
  class QueryFieldProto extends MessageLiteImpl
  class UOWNotificationProto extends MessageLiteImpl
  class PartitionedUOWNotificationProto extends MessageLiteImpl
  class PartitionedUOWNotificationKeyProto extends MessageLiteImpl
  class UOWApplicationEventProto extends MessageLiteImpl
  class AssertValidProto extends MessageLiteImpl
  class AssertValidResultProto extends MessageLiteImpl
  class PutProto extends MessageLiteImpl
  class PutResultProto extends MessageLiteImpl
  class AccMetadataCommandProto extends MessageLiteImpl
  class AccTableResultProto extends MessageLiteImpl
  class ResolveKeysProto extends MessageLiteImpl
  class ResolveKeysResultProto extends MessageLiteImpl
  class WriteBusinessEventProto extends MessageLiteImpl
  class SerializedEntityTupleProto extends MessageLiteImpl
  class PutSlotsProto extends MessageLiteImpl
  class EntityReferenceTupleProto extends MessageLiteImpl
  class WriteBusinessEventResultProto extends MessageLiteImpl
  class PutApplicationEventResultProto extends MessageLiteImpl
  class PutApplicationEventProto extends MessageLiteImpl
  class InvalidateAfterProto extends MessageLiteImpl
  class InvalidateAfterResultProto extends MessageLiteImpl
  class InvalidateAllCurrentProto extends MessageLiteImpl
  class InvalidateAllCurrentResultProto extends MessageLiteImpl
  class InvalidateAllCurrentByRefsProto extends MessageLiteImpl
  class CreateSlotsProto extends MessageLiteImpl
  class CreateSlotsResultProto extends MessageLiteImpl
  class FillSlotProto extends MessageLiteImpl
  class PathElementProto extends MessageLiteImpl
  class SlotRedirectionInfoProto extends MessageLiteImpl
  class VersioningRedirectionInfoProto extends MessageLiteImpl
  class IsEntitledProto extends MessageLiteImpl
  class IsEntitledResultProto extends MessageLiteImpl
  class ExpressionProto extends MessageLiteImpl
  class EntityBitempSpaceProto extends MessageLiteImpl
  class EntityProto extends MessageLiteImpl
  class EventProto extends MessageLiteImpl
  class LinkageProto extends MessageLiteImpl
  class EmbeddableProto extends MessageLiteImpl
  class PropertyProto extends MessageLiteImpl
  class ConstantProto extends MessageLiteImpl
  class BinaryProto extends MessageLiteImpl
  class InProto extends MessageLiteImpl
  class JoinProto extends MessageLiteImpl
  class MemberProto extends MessageLiteImpl
  class FunctionProto extends MessageLiteImpl
  class UnaryProto extends MessageLiteImpl
  class ConditionProto extends MessageLiteImpl
  class AggregateProto extends MessageLiteImpl
  class ScalarProto extends MessageLiteImpl
  class ExistsProto extends MessageLiteImpl
  class TypeCodeProto extends MessageLiteImpl
  class PropertyDefProto extends MessageLiteImpl
  class SortByDefProto extends MessageLiteImpl
  class SilverKingTraceIdProto extends MessageLiteImpl
  class BitempRangeProto extends MessageLiteImpl
  class EntityBusinessEventWithTTToComboProto extends MessageLiteImpl
  class EntityBusinessEventComboProto extends MessageLiteImpl
  class VersioningResponseProto extends MessageLiteImpl
  class TimingsProto extends MessageLiteImpl
  object DSIRequestProto {
    class Type
  }
  class DalResponseProto extends MessageLiteImpl
  class NamespaceProto extends MessageLiteImpl
  class TemporalContextProto extends MessageLiteImpl
  class TemporalSurfaceMatcherProto extends MessageLiteImpl
  class DSIResponseProto extends MessageLiteImpl
  class RelationElementProto extends MessageLiteImpl
  class ClassEntityInfoProto extends MessageLiteImpl
}