package optimus

import sbt._

object Dependencies {
  val akkaVersion = "2.6.20"
  val akkaHttpVersion = "10.2.10"
  val asmVersion = "9.7.1"
  val curatorVersion = "5.7.1"
  val cxfVersion = "3.6.4"
  val guiceVersion = "7.0.0"
  val httpComponentsVersion = "4.5.14"
  val jacksonVersion = "2.18.2"
  val kafkaVersion = "3.9.0"
  val logbackVersion = "1.5.12"
  val nettyVersion = "4.1.115.Final"
  val scala2Version = "2.13.15"
  val springVersion = "6.2.0"

  val akkaActor = "com.typesafe.akka" %% "akka-actor" % akkaVersion
  val akkaHttpCore = "com.typesafe.akka" %% "akka-http-core" % akkaHttpVersion
  val akkaHttpSprayJson = "com.typesafe.akka" %% "akka-http-spray-json" % akkaHttpVersion
  val akkaStream = "com.typesafe.akka" %% "akka-stream" % akkaVersion
  val archaiusCore = "com.netflix.archaius" % "archaius-core" % "0.7.12"
  val args4j = "args4j" % "args4j" % "2.37"
  val asm = "org.ow2.asm" % "asm" % asmVersion
  val asmCommons = "org.ow2.asm" % "asm-commons" % asmVersion
  val asmTree = "org.ow2.asm" % "asm-tree" % asmVersion
  val asmUtil = "org.ow2.asm" % "asm-util" % asmVersion
  val asyncProfilerLoaderAll = "me.bechberger" % "ap-loader-all" % "3.0-9"
  val awsSdk = "com.amazonaws" % "aws-java-sdk" % "1.12.779"
  val base64 = "net.iharder" % "base64" % "2.3.9"
  val bsp4j = "ch.epfl.scala" % "bsp4j" % "2.1.0"
  val caffeine = "com.github.ben-manes.caffeine" % "caffeine" % "3.1.8"
  val caliper = "com.google.caliper" % "caliper" % "1.0-beta-3"
  val commonsCompress = "org.apache.commons" % "commons-compress" % "1.27.1"
  val commonsIO = "commons-io" % "commons-io" % "2.18.0"
  val commonsLang3 = "org.apache.commons" % "commons-lang3" % "3.17.0"
  val commonsMath3 = "org.apache.commons" % "commons-math3" % "3.6.1"
  val coursier = "io.get-coursier" %% "coursier" % "2.0.16"
  val curatorRecipes = "org.apache.curator" % "curator-recipes" % curatorVersion
  val curatorFramework = "org.apache.curator" % "curator-framework" % curatorVersion
  val cxfTools = "org.apache.cxf" % "cxf-tools-common" % cxfVersion
  val cxfToolsWsdlto = "org.apache.cxf" % "cxf-tools-wsdlto-core" % cxfVersion
  val eaioUUID = "com.eaio.uuid" % "uuid" % "3.2"
  val fastUtil = "it.unimi.dsi" % "fastutil" % "8.5.15"
  val freemarker = "org.freemarker" % "freemarker" % "2.3.33"
  val guava = "com.google.guava" % "guava" % "33.3.1-jre"
  val guice = "com.google.inject" % "guice" % guiceVersion
  val guiceAssistedInject = "com.google.inject.extensions" % "guice-assistedinject" % guiceVersion
  val hamcrest = "org.hamcrest" % "hamcrest" % "3.0"
  val hdrHistogram = "org.hdrhistogram" % "HdrHistogram" % "2.2.2"
  val hibernateValidator = "org.hibernate.validator" % "hibernate-validator" % "8.0.1.Final"
  val hkdf = "at.favre.lib" % "hkdf" % "1.1.0"
  val httpClient = "org.apache.httpcomponents" % "httpclient" % httpComponentsVersion
  val httpMime = "org.apache.httpcomponents" % "httpmime" % httpComponentsVersion
  val jansi = "org.fusesource.jansi" % "jansi" % "2.4.1"
  val jakartaInject = "jakarta.inject" % "jakarta.inject-api" % "2.0.1"
  val javaxActivation = "javax.activation" % "activation" % "1.1.1"
  val javaxMail = "javax.mail" % "javax.mail-api" % "1.6.2"
  val jacksonDatabind = "com.fasterxml.jackson.core" % "jackson-databind" % jacksonVersion
  val jacksonDataformatYaml = "com.fasterxml.jackson.dataformat" % "jackson-dataformat-yaml" % jacksonVersion
  val jacksonDatatypeJSR310 = "com.fasterxml.jackson.datatype" % "jackson-datatype-jsr310" % jacksonVersion
  val jacksonModuleScala = "com.fasterxml.jackson.module" %% "jackson-module-scala" % jacksonVersion
  val jcTools = "org.jctools" % "jctools-core" % "4.0.5"
  val jettison = "org.codehaus.jettison" % "jettison" % "1.5.4"
  val jgit = "org.eclipse.jgit" % "org.eclipse.jgit" % "7.1.0.202411261347-r"
  val jgrapht = "org.jgrapht" % "jgrapht-core" % "1.3.1"
  val jibCore = "com.google.cloud.tools" % "jib-core" % "0.27.2"
  val jmustache = "com.samskivert" % "jmustache" % "1.16"
  val jnaPlatform = "net.java.dev.jna" % "jna-platform" % "5.15.0"
  val jodaTime = "joda-time" % "joda-time" % "2.13.0"
  val jsonSchema2Pojo = "org.jsonschema2pojo" % "jsonschema2pojo-core" % "1.2.2"
  val junit = "junit" % "junit" % "4.13.2"
  val kafka = "org.apache.kafka" %% "kafka" % kafkaVersion
  val kafkaClients = "org.apache.kafka" % "kafka-clients" % kafkaVersion
  val logbackClassic = "ch.qos.logback" % "logback-classic" % logbackVersion
  val logbackCore = "ch.qos.logback" % "logback-core" % logbackVersion
  val nettyBuffer = "io.netty" % "netty-buffer" % nettyVersion
  val nettyHandler = "io.netty" % "netty-handler" % nettyVersion
  val nettyResolverDNS = "io.netty" % "netty-resolver-dns" % nettyVersion
  val openCSV = "com.opencsv" % "opencsv" % "5.9"
  val poi = "org.apache.poi" % "poi" % "5.3.0"
  val scalaCollectionCompat = "org.scala-lang.modules" %% "scala-collection-compat" % "2.12.0"
  val scalaCompiler = "org.scala-lang" % "scala-compiler" % scala2Version
  val scalaParallelCollections = "org.scala-lang.modules" %% "scala-parallel-collections" % "0.2.0"
  val scalaParserCombinator = "org.scala-lang.modules" %% "scala-parser-combinators" % "1.1.2"
  val scalaReflect = "org.scala-lang" % "scala-reflect" % scala2Version
  val scalaxb = "org.scalaxb" %% "scalaxb" % "1.8.3"
  val scalaXml = "org.scala-lang.modules" %% "scala-xml" % "1.3.1"
  val slf4j = "org.slf4j" % "slf4j-api" % "2.0.16"
  val snakeYaml = "org.yaml" % "snakeyaml" % "2.3"
  val sprayJson = "io.spray" %% "spray-json" % "1.3.6"
  val springContext = "org.springframework" % "spring-context" % springVersion
  val springWeb = "org.springframework" % "spring-web" % springVersion
  val typesafeConfig = "com.typesafe" % "config" % "1.4.3"
  val zooKeeper = "org.apache.zookeeper" % "zookeeper" % "3.9.3"
  val zinc = "org.scala-sbt" %% "zinc" % "1.7.2"
  val zstdJni = "com.github.luben" % "zstd-jni" % "1.5.6-8"
}